run:
  timeout: 3m
  modules-download-mode: readonly
  go: '1.23' # 프로젝트의 버전 지정
linters:
  enable:
    - goimports
    - errname # sentinel error는 Err(err)로 시작하는지, 타입은 Error Suffix가 있는지 확인
    - bodyclose # response body가 잘 닫혔는지 확인
    - revive # 여러가지 린터, 아래 규칙들 확인
    # 기본으로 켜져있는 것들
    # errcheck: 체크되지 않는 에러가 있는지
    # gosimple: code simplifying
    # govet: 컴파일러에게 잡히지 않는 에러들 체크
    # ineffassign: 사용되지 않는 이미 존재하는 변수에 할당하는 경우 (불필요한 할당)
    # staticcheck: 퍼포먼스 이슈, simplifying, 규칙들 강제
    # unused: 사용되지 않는 식별자 확인

linters-settings:
  goimports:
    local-prefixes: "github.com/worlp"
  revive:
    severity: error
    rules:
      # 컨텍스트를 맨 앞에
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
      - name: context-as-argument
        severity: error
        disabled: false

      # 에러가 리턴 중 맨 마지막인지 확인
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-return
      - name: error-return
        severity: error
        disabled: false

      # builtin 식별자를 쉐도잉하는지 확인
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#redefines-builtin-id
      - name: redefines-builtin-id
        severity: error
        disabled: false

      # WARN Level
      # 일반적인 변수 이름 컨벤션 확인 (두문자어, 패키지 이름, 변수 이름 등)
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
      - name: var-naming
        severity: warning
        disabled: false

      # 사용되지 않는 parameter 확인
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: false